#!/bin/bash

install()
{
	if command hash "brew" > "/dev/null" 2>&1
	then
		command declare base
		command declare module
		command declare -a modules

		base="$(command dirname ${BASH_SOURCE[0]})"
		modules=("${@}")

		if command test -z "${modules}"
		then
			for module in "${base}/modules"/*/
			do
				module="$(basename ${module})"
				modules+=(${module})
			done
		fi

		for module in "${modules[@]}"
		do
			if command test ! -d "${base}/modules/${module}"
			then
				command echo "Module ${module} not found"
				command continue
			fi

			command echo "Module: ${module}"

			module="${base}/modules/${module}"

			if command test -r "${module}/install.sh"
			then
				command echo "	Running module installation script"
				command source "${module}/install.sh" >> "${module}/install.log"
			fi
		done

		command unset -v base
		command unset -v module
		command unset -v modules
		command return 0
	else
		command echo "Installing Homebrew"
		/usr/bin/ruby -e "$(command curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" > "/dev/null"
		install "${@}"
	fi
}

(install "${@}")

command unset -f install
